sudo: required
services:
  - docker
before_install: 
  - docker build -t kartiktickoo/docker-react -f Dockerfile.dev .
script: 
  - docker run -e CI=true kartiktickoo/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "elasticbeanstalk-us-east-2-436382833053"
  bucket-path: "react-app"
  region: "us-east-2"
  app: "react-app"
  env: React-app-env
  edge: true # opt in to dpl v2