sudo: required
services:
  - docker
before_install: 
  - docker build -t kartiktickoo/docker-react -f Dockerfile.dev .
script: 
  - docker run -e CI=true kartiktickoo/docker-react npm run test -- --coverage